/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author JESS
 */
public class ViewCifrador extends javax.swing.JFrame {

    /**
     * Creates new form ViewCifrador
     */
    public ViewCifrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTA_TEXTO = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        JM_ARCHIVO = new javax.swing.JMenu();
        JM_ABRIR = new javax.swing.JMenuItem();
        JM_CIFRAR = new javax.swing.JMenuItem();
        JM_DESCIFRAR = new javax.swing.JMenuItem();
        JM_GUARDAR = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTA_TEXTO.setColumns(20);
        JTA_TEXTO.setRows(5);
        jScrollPane1.setViewportView(JTA_TEXTO);

        jMenuBar1.setBackground(new java.awt.Color(51, 102, 255));

        JM_ARCHIVO.setText("ARCHIVO");

        JM_ABRIR.setText("ABRIR");
        JM_ARCHIVO.add(JM_ABRIR);

        JM_CIFRAR.setText("CIFRAR");
        JM_ARCHIVO.add(JM_CIFRAR);

        JM_DESCIFRAR.setText("DESCIFRAR");
        JM_ARCHIVO.add(JM_DESCIFRAR);

        JM_GUARDAR.setText("GUARDAR");
        JM_ARCHIVO.add(JM_GUARDAR);

        jMenuBar1.add(JM_ARCHIVO);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCifrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCifrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCifrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCifrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCifrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem JM_ABRIR;
    private javax.swing.JMenu JM_ARCHIVO;
    public javax.swing.JMenuItem JM_CIFRAR;
    public javax.swing.JMenuItem JM_DESCIFRAR;
    public javax.swing.JMenuItem JM_GUARDAR;
    public javax.swing.JTextArea JTA_TEXTO;
    public javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
